// flow-typed signature: c203206910ab7450997909707d514a33
// flow-typed version: <<STUB>>/temporary_v^0.0.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'temporary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'temporary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'temporary/examples/dir' {
  declare module.exports: any;
}

declare module 'temporary/examples/file' {
  declare module.exports: any;
}

declare module 'temporary/lib/base' {
  declare module.exports: any;
}

declare module 'temporary/lib/detector' {
  declare module.exports: any;
}

declare module 'temporary/lib/dir' {
  declare module.exports: any;
}

declare module 'temporary/lib/file' {
  declare module.exports: any;
}

declare module 'temporary/lib/generator' {
  declare module.exports: any;
}

declare module 'temporary/test/base.test' {
  declare module.exports: any;
}

declare module 'temporary/test/detector.test' {
  declare module.exports: any;
}

declare module 'temporary/test/dir.test' {
  declare module.exports: any;
}

declare module 'temporary/test/file.test' {
  declare module.exports: any;
}

declare module 'temporary/test/generator.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'temporary/examples/dir.js' {
  declare module.exports: $Exports<'temporary/examples/dir'>;
}
declare module 'temporary/examples/file.js' {
  declare module.exports: $Exports<'temporary/examples/file'>;
}
declare module 'temporary/index' {
  declare module.exports: $Exports<'temporary'>;
}
declare module 'temporary/index.js' {
  declare module.exports: $Exports<'temporary'>;
}
declare module 'temporary/lib/base.js' {
  declare module.exports: $Exports<'temporary/lib/base'>;
}
declare module 'temporary/lib/detector.js' {
  declare module.exports: $Exports<'temporary/lib/detector'>;
}
declare module 'temporary/lib/dir.js' {
  declare module.exports: $Exports<'temporary/lib/dir'>;
}
declare module 'temporary/lib/file.js' {
  declare module.exports: $Exports<'temporary/lib/file'>;
}
declare module 'temporary/lib/generator.js' {
  declare module.exports: $Exports<'temporary/lib/generator'>;
}
declare module 'temporary/test/base.test.js' {
  declare module.exports: $Exports<'temporary/test/base.test'>;
}
declare module 'temporary/test/detector.test.js' {
  declare module.exports: $Exports<'temporary/test/detector.test'>;
}
declare module 'temporary/test/dir.test.js' {
  declare module.exports: $Exports<'temporary/test/dir.test'>;
}
declare module 'temporary/test/file.test.js' {
  declare module.exports: $Exports<'temporary/test/file.test'>;
}
declare module 'temporary/test/generator.test.js' {
  declare module.exports: $Exports<'temporary/test/generator.test'>;
}
